In [1]:
from CCDM import encode
from CCDM_utils import initialize
import numpy as np

In [2]:
pOpt = [0.1,0.1,0.3,0.5]
nSyms = 10
n_i, p_iter_dis_quant, num_info_bits = initialize(pOpt, nSyms)

[2. 2. 3. 3.]
[0.2 0.2 0.3 0.3]


In [3]:
num_info_bits = 12
n_i = [1, 1, 3, 5]
p_iter_dis_quant = [0.1, 0.1, 0.3, 0.5]
src_symbols = np.random.randint(0,2,num_info_bits)

In [5]:
code_symbols = encode(src_symbols, nSyms, n_i)
code_symbols

0
0.1
1
0.0
2
0.3
3
0.5


IndexError: list assignment index out of range

In [7]:
k = np.array([1.0])
print((k[0]/2) == 0.5)

True


In [8]:
code = [1,0,0, 23,44535,65,876]

In [22]:
code_enumerate = enumerate(code)
code_enumerate.

AttributeError: 'enumerate' object has no attribute '1'

In [14]:
code_iterator = iter(code)
code_iterator.__next__()

1

In [16]:
code_iter = code_iterator
code_iter.__next__()

In [23]:
print(([1,2] == [1,2]))

True


In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
b = np.array([[2],[3]])
a*b

array([[ 2,  4,  6,  8, 10],
       [15, 12,  9,  6,  3]])

In [3]:
angle = np.array([[1],[2],[3]])
angle_copy = np.expand_dims(angle, -1)
angle_copy

array([[[1]],

       [[2]],

       [[3]]])

In [4]:
signal = np.array([[[3],[6],[9]],[[2],[5],[8]],[[1],[4],[7]]])
print(signal * angle_copy)

[[[ 3]
  [ 6]
  [ 9]]

 [[ 4]
  [10]
  [16]]

 [[ 3]
  [12]
  [21]]]


In [6]:
Ak = np.zeros([2,4])
v0 = np.array([[1], [8]])
vk = v0
# 构建星座平方块矩阵
blockreal = np.array([1,2,3,4])
blockimag = np.array([4,3,2,1])

Ak[0] = blockreal
Ak[1] = blockimag
Ck = np.matmul(Ak, Ak.transpose())
print("Ck: " + str(Ck))
vk = np.matmul(Ck, vk)
vk = vk / np.sqrt(np.sum(vk ** 2))
print("vk: " + str(vk))
phiK = 0.5 * np.arctan2(vk[0][0], vk[1][0]) - (np.pi / 4)
print(phiK)

Ck: [[30. 20.]
 [20. 30.]]
vk: [[0.59001659]
 [0.80739112]]
-0.46985846966178363


In [1]:
import numpy as np

In [2]:
matrix = np.array([[23,53454,64565],[23232,534654,65756]])

In [6]:
np.expand_dims(matrix.transpose()[0],-1)

array([[   23],
       [23232]])

In [1]:
import numpy as np

In [2]:
ϕ_test = np.arange(0, 64) * (np.pi / 2) / 64  # test phases
ϕ_test

array([0.        , 0.02454369, 0.04908739, 0.07363108, 0.09817477,
       0.12271846, 0.14726216, 0.17180585, 0.19634954, 0.22089323,
       0.24543693, 0.26998062, 0.29452431, 0.319068  , 0.3436117 ,
       0.36815539, 0.39269908, 0.41724277, 0.44178647, 0.46633016,
       0.49087385, 0.51541754, 0.53996124, 0.56450493, 0.58904862,
       0.61359232, 0.63813601, 0.6626797 , 0.68722339, 0.71176709,
       0.73631078, 0.76085447, 0.78539816, 0.80994186, 0.83448555,
       0.85902924, 0.88357293, 0.90811663, 0.93266032, 0.95720401,
       0.9817477 , 1.0062914 , 1.03083509, 1.05537878, 1.07992247,
       1.10446617, 1.12900986, 1.15355355, 1.17809725, 1.20264094,
       1.22718463, 1.25172832, 1.27627202, 1.30081571, 1.3253594 ,
       1.34990309, 1.37444679, 1.39899048, 1.42353417, 1.44807786,
       1.47262156, 1.49716525, 1.52170894, 1.54625263])

In [4]:
array = np.array([[2,3,4],[3,6,9],[1,2,3]])
print(np.sum(array,axis=0))

[ 6 11 16]


In [4]:
import sys

In [5]:
sys.path.append("..")

In [6]:
sys.path.append("../..")

In [7]:
import probabilisticShaping

e:\Anaconda\envs\OptiCommPy\lib\site-packages\numba\__init__.py:44: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.23.0)
  import scipy


In [14]:
ps = probabilisticShaping.probabilisticShaping(64,0.2, 10000)

In [15]:
ps.genSymbols()

34039


[(-2.8979659500488224+2.8979659500488224j),
 (-8.693897850146467-2.8979659500488224j),
 (2.8979659500488224+8.693897850146467j),
 (2.8979659500488224+8.693897850146467j),
 (-2.8979659500488224+2.8979659500488224j),
 (-2.8979659500488224-2.8979659500488224j),
 (-2.8979659500488224-2.8979659500488224j),
 (-2.8979659500488224+2.8979659500488224j),
 (-2.8979659500488224+2.8979659500488224j),
 (-2.8979659500488224-2.8979659500488224j),
 (2.8979659500488224-2.8979659500488224j),
 (-2.8979659500488224+8.693897850146467j),
 (2.8979659500488224-2.8979659500488224j),
 (-2.8979659500488224-2.8979659500488224j),
 (2.8979659500488224-2.8979659500488224j),
 (2.8979659500488224+2.8979659500488224j),
 (2.8979659500488224+2.8979659500488224j),
 (2.8979659500488224+2.8979659500488224j),
 (2.8979659500488224-2.8979659500488224j),
 (2.8979659500488224-2.8979659500488224j),
 (-2.8979659500488224-2.8979659500488224j),
 (-2.8979659500488224-8.693897850146467j),
 (2.8979659500488224-2.8979659500488224j),
 (2.